"""initial schema with check constraints

Revision ID: f40fa31b803c
Revises:
Create Date: 2026-03-29 02:18:56.392901

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f40fa31b803c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "members",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("deductible", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("deductible >= 0", name="ck_plans_deductible_non_negative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "providers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("npi", sa.String(length=20), nullable=False),
        sa.Column(
            "provider_type", sa.Enum("individual", "facility", name="providertype"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("npi"),
    )
    op.create_table(
        "coverage_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("cpt_code", sa.String(length=20), nullable=False),
        sa.Column("is_covered", sa.Boolean(), nullable=False),
        sa.Column("coverage_percentage", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "coverage_percentage >= 0 AND coverage_percentage <= 1",
            name="ck_coverage_rules_percentage_range",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "policies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status", sa.Enum("active", "expired", "cancelled", name="policystatus"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("end_date >= start_date", name="ck_policies_end_after_start"),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "accumulators",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.Column("policy_id", sa.String(length=36), nullable=False),
        sa.Column("deductible_met", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "deductible_met >= 0", name="ck_accumulators_deductible_met_non_negative"
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id", "policy_id", name="uq_accumulator_member_policy"),
        sa.UniqueConstraint("policy_id"),
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.Column("policy_id", sa.String(length=36), nullable=False),
        sa.Column("provider_id", sa.String(length=36), nullable=False),
        sa.Column("date_of_service", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "submitted",
                "under_review",
                "approved",
                "denied",
                "partially_approved",
                "paid",
                name="claimstatus",
            ),
            nullable=False,
        ),
        sa.Column("review_type", sa.Enum("auto", "manual", name="reviewtype"), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "claim_status_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("claim_id", sa.String(length=36), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "submitted",
                "under_review",
                "approved",
                "denied",
                "partially_approved",
                "paid",
                name="claimstatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "submitted",
                "under_review",
                "approved",
                "denied",
                "partially_approved",
                "paid",
                name="claimstatus",
            ),
            nullable=False,
        ),
        sa.Column("transitioned_at", sa.DateTime(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "disputes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("claim_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("reviewer_note", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.Enum("pending", "resolved", name="disputestatus"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("claim_id"),
    )
    op.create_table(
        "line_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("claim_id", sa.String(length=36), nullable=False),
        sa.Column("diagnosis_code", sa.String(length=20), nullable=False),
        sa.Column("cpt_code", sa.String(length=20), nullable=False),
        sa.Column("billed_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "adjudication_status",
            sa.Enum("pending", "approved", "denied", name="lineitemstatus"),
            nullable=False,
        ),
        sa.Column("latest_result_id", sa.String(length=36), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("billed_amount > 0", name="ck_line_items_billed_amount_positive"),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
        ),
        sa.ForeignKeyConstraint(
            ["latest_result_id"],
            ["adjudication_results.id"],
            name="fk_line_item_latest_result",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("claim_id", sa.String(length=36), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("amount >= 0", name="ck_payments_amount_non_negative"),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("claim_id"),
    )
    op.create_table(
        "adjudication_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("line_item_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("is_covered", sa.Boolean(), nullable=False),
        sa.Column("applied_to_deductible", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("plan_pays", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("member_owes", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("adjudicated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "applied_to_deductible >= 0", name="ck_adjudication_results_applied_non_negative"
        ),
        sa.CheckConstraint(
            "member_owes >= 0", name="ck_adjudication_results_member_owes_non_negative"
        ),
        sa.CheckConstraint("plan_pays >= 0", name="ck_adjudication_results_plan_pays_non_negative"),
        sa.CheckConstraint("revision >= 1", name="ck_adjudication_results_revision_min"),
        sa.ForeignKeyConstraint(
            ["line_item_id"],
            ["line_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("line_item_id", "revision", name="uq_adjudication_line_revision"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("adjudication_results")
    op.drop_table("payments")
    op.drop_table("line_items")
    op.drop_table("disputes")
    op.drop_table("claim_status_history")
    op.drop_table("claims")
    op.drop_table("accumulators")
    op.drop_table("policies")
    op.drop_table("coverage_rules")
    op.drop_table("providers")
    op.drop_table("plans")
    op.drop_table("members")
    # ### end Alembic commands ###
